#Nombre del workflow
name: Continuous Integration / Continuous Delivery

#Con esta se hace sólo en la configuración de push a master/main
on:
  push:
    branches:
      - main

jobs:
  #Nombre del proceso
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar la última version del código
        uses: actions/checkout@v4

      - name: Configurar un ambiente de nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

  continuous-delivery:
    needs: continuous-integration
    runs-on: ubuntu-latest
    steps: 
      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.0 #Me permite conectarme a un servidor por medio de ssh
        with: 
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          script: | 
            cd bedu-pf-fsd-frontend-2023
            git pull origin main
            yarn install --production
            pm2 restart src/main.jsx
            

